name: dataforger
channels:
  - conda-forge
dependencies:
  - pyspark >= 2.4
  - python = 3.8
  - pyspark-stubs
  - click >= 7.1
  - flit
  - colorama
  - tornado
  - pydata-sphinx-theme
  - sphinx
  - pyyaml
  - schema